const fs = require('node:fs');
const path = require('node:path');
const copy = require('./content/approved-copy.json');
const wpSettings = require('./content/wordpress-settings.json');
const esc = s => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const s = n => copy[n-1].blocks;
const hp = 'http://b.hpr.jp/kr/hp/H000729373';
const line = 'https://lin.ee/vu0eLpN';
const map = 'https://share.google/o2JoXzL2cJp1a2v7E';
const inline = t => esc(t.replace(/\n↓\s*$/,'')).replace(/\n→ 公式LINE：https:\/\/lin.ee\/vu0eLpN/g, `<br><a href="${line}" target="_blank" rel="noopener">公式LINEへ相談する <span aria-hidden="true">↗</span></a>`).replaceAll('\n','<wbr>');
const p = (t, cls='') => `<p${cls ? ` class="${cls}"` : ''}>${inline(t)}</p>`;
const heading = (t,tag='h2') => `<${tag}>${esc(t).replaceAll('\n','<br>')}</${tag}>`;
const label = (n,en) => `<div class="section-label"><span>${String(n).padStart(2,'0')}</span><span>${en}</span><i></i></div>`;
const image = (file,alt,cls='',eager=false) => `<img class="${cls}" src="images/${file}.webp" alt="${alt}" width="${file==='profile-onishi'?'1824':file==='shop-exterior'?'1125':file==='treatment-hands'?'1080':'4032'}" height="${file==='profile-onishi'?'2432':file==='shop-exterior'?'693':file==='treatment-hands'?'1080':'3024'}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const btn = (t,url=hp,cls='') => `<a class="button ${cls}" href="${url}" ${url.startsWith('tel:')?'':'target="_blank" rel="noopener"'}><span>${esc(t)}</span><span aria-hidden="true">${url.startsWith('tel:')?'↗':'↗'}</span></a>`;
const fromButton = (t, cls='') => {const [name,url] = t.split('\n'); return btn(name.replace('［ボタン］',''),url.replace('→ ','').replace(/^090-9374-5073$/,'tel:09093745073'),cls)};
const list = (t,cls='')=>`<ul class="${cls}">${t.split('\n').map(x=>`<li>${inline(x.replace(/^[☑・]\s*/,''))}</li>`).join('')}</ul>`;
const step = (n,title,text,img,extra='')=>`<article class="flow-step"><div class="step-photo">${image(img,title)}</div><div class="step-copy"><span class="step-number">${n}</span>${heading(title,'h3')}${p(text)}${extra?p(extra):''}</div></article>`;
const sourceStep = (i,img,extra='')=>{const [head,...body]=s(5)[i].split('\n');const [n,title]=head.split('｜');return step(n,title,body.join('\n'),img,extra)};
const pages = [];
pages.push(`<section id="home" class="hero" data-section="01"><div class="hero-main"><div class="hero-copy"><p class="hero-audience">${inline(s(1)[0])}</p><div class="hero-rule"></div><h1>肩こり・腰のつらさを、<br>その場しのぎで<br><em>終わらせない。</em></h1>${p(s(1)[2],'hero-message')}${p(s(1)[5],'hero-location')}${fromButton(s(1)[6])}</div><figure class="hero-image">${image('check-posture','理学療法士の大西英一郎が、女性のお客様の身体の状態を確認している様子','',true)}<figcaption><span>total life support</span><strong>clear</strong></figcaption></figure></div><div class="hero-intro wrap"><div>${heading(s(1)[3])}</div><div>${p(s(1)[4])}</div></div></section>`);
pages.push(`<section id="concerns" class="section concerns" data-section="02"><div class="wrap split"><div class="section-aside">${label(2,'YOUR BODY')}${heading('こんなお悩み、<br>ありませんか？'.replace('<br>','\n'))}<figure class="offset-photo">${image('treatment-hands','肩にやさしく手を添える施術の様子')}<span class="photo-index" aria-hidden="true">clear — care for yourself</span></figure></div><div class="concern-content">${list(s(2)[0],'check-list')}${p(s(2)[1],'serif statement')}${p(s(2)[2])}</div></div></section>`);
pages.push(`<section id="approach" class="section approach" data-section="03"><div class="wrap"><div class="split approach-intro"><div>${label(3,'OUR APPROACH')}${heading(s(3)[0])}${p(s(3)[1])}${p(s(3)[2],'strong')}${p(s(3)[3])}</div><figure class="arched-photo">${image('selfcare-exercise','身体を動かしながら、お客様に合わせたケアを確認する様子')}</figure></div><div class="principles-heading">${heading(s(3)[4],'h3')}<span aria-hidden="true">01 — 03</span></div><div class="principles">${s(3).slice(5).map((b,i)=>{let [title,...body]=b.split('\n');return `<article><span class="large-number">0${i+1}</span>${heading(title.split('｜')[1],'h3')}${p(body.join('\n'))}</article>`}).join('')}</div></div></section>`);
const credentials=s(4)[4].split('\n');
pages.push(`<section id="profile" class="section profile dark" data-section="04"><div class="wrap"><div class="split profile-top"><div class="profile-photo">${label(4,'YOUR THERAPIST')}${image('profile-onishi','担当する理学療法士、大西英一郎')}<div class="nameplate"><span>理学療法士</span><strong>大西 英一郎</strong></div></div><div class="profile-copy">${heading(s(4)[0])}${s(4).slice(1,4).map(x=>p(x)).join('')}<div class="signature" aria-hidden="true">Eiichiro Onishi</div></div></div><div class="credentials"><p class="credentials-date">${esc(credentials[0])}</p><div class="rating-row">${credentials.slice(1,3).map(t=>{const m=t.match(/・(.+?) ([\d.]+)（(.+)）/);return `<div><span>${m[1]}</span><div><strong>${m[2]}</strong><span>（${m[3]}）</span></div></div>`}).join('')}</div>${list(credentials.slice(3).join('\n'),'credential-list')}</div></div></section>`);
pages.push(`<section id="flow" class="section flow" data-section="05"><div class="wrap"><div class="flow-heading">${label(5,'FIRST VISIT')}${heading(copy[4].title)}${p(s(5)[0],'serif statement')}${p(s(5)[1])}</div><div class="steps">${sourceStep(2,'profile-onishi')}${sourceStep(3,'check-posture')}${sourceStep(4,'treatment-hands')}${sourceStep(5,'selfcare-exercise',s(5)[6])}${sourceStep(7,'check-posture')}</div><div class="center-action">${fromButton(s(5)[8])}</div></div></section>`);
pages.push(`<section id="salon" class="section salon" data-section="06"><div class="wrap"><div class="split"><div>${label(6,'A PLACE FOR YOU')}${heading(s(6)[0])}${p(s(6)[1])}${p(s(6)[2])}</div><figure class="salon-exterior">${image('shop-exterior','clearがある、おおにし産婦人科の建物外観')}</figure></div><div class="salon-bottom"><div>${heading(s(6)[3].split('\n')[0],'h3')}${list(s(6)[3].split('\n').slice(1).join('\n'),'check-list')}</div><div class="salon-note">${p(s(6)[4],'serif')}</div></div></div></section>`);
pages.push(`<section id="price" class="section price dark" data-section="07"><div class="wrap"><div class="price-layout"><div class="price-intro">${label(7,'MENU & PRICE')}${heading(copy[6].title)}${image('selfcare-exercise','オーダーメイドの整体と運動・セルフケアの様子')}</div><div class="price-card"><p class="price-title">オーダーメイド整体 <span>60分</span></p><p class="regular-price">通常 <span>8,000円</span> <span aria-hidden="true">↓</span></p><div class="first-price"><span>初回</span><strong>4,000</strong><span>円</span></div><div class="price-includes">${s(7)[1].split('\n').map(x=>`<p>${inline(x)}</p>`).join('')}</div><div class="repeat-price">${p(s(7)[2])}</div></div></div></div></section>`);
pages.push(`<section id="reservation" class="section reservation" data-section="08"><div class="wrap"><div class="reservation-header"><div>${label(8,'RESERVATION')}${heading(copy[7].title)}</div>${image('treatment-hands','身体の状態に合わせた、手による丁寧なケア')}</div><div class="booking-options"><article><span class="option-number">01</span>${p(s(8)[0])}${fromButton(s(8)[1])}</article><article><span class="option-number">02</span>${p(s(8)[2])}${fromButton(s(8)[3],'button-green')}</article><article class="phone-option"><div><span class="option-number">03</span>${p(s(8)[4])}</div><div>${fromButton(s(8)[5],'button-outline')}<a class="phone-number" href="tel:09093745073">090-9374-5073</a></div></article></div></div></section>`);
const faqItems=s(9).filter(x=>x.startsWith('Q. '));
pages.push(`<section id="faq" class="section faq" data-section="09"><div class="wrap faq-layout"><div class="faq-intro">${label(9,'QUESTIONS')}${heading('よくある\nご質問')}${image('profile-onishi','ご相談をお伺いする理学療法士、大西英一郎')}</div><div class="faq-items">${faqItems.map((b,i)=>{const [q,...answer]=b.split('\n');return `<details ${i===0?'open':''}><summary><span class="q-mark" aria-hidden="true">Q.</span><span>${esc(q.replace('Q. ',''))}</span><span class="faq-toggle" aria-hidden="true"></span></summary><div class="faq-answer">${p(answer.join('\n'))}<!-- Approved testimonial screenshot slot: question ${i+1}. Add the supplied screenshot here when received; do not invent a review. --></div></details>`}).join('')}</div></div></section>`);
pages.push(`<section id="voices" class="section voices" data-section="10"><div class="wrap"><div class="voices-header"><div>${label(10,'VOICES')}${heading(s(10)[0])}${p(s(10)[1])}</div>${image('check-posture','サロンで身体の状態を確認している様子。口コミ投稿者の写真ではありません。')}</div><div class="voice-list">${s(10).slice(2,5).map((b,i)=>{const [quote,by]=b.split('\n');return `<figure class="voice"><span class="quote-mark" aria-hidden="true">“</span><blockquote>${p(quote)}</blockquote><figcaption>${esc(by)}</figcaption><!-- Client review screenshot ${i+1}: pending delivery. --></figure>`}).join('')}</div>${p(s(10)[5],'fineprint')}<div class="center-action">${fromButton(s(10)[6])}</div></div></section>`);
pages.push(`<section id="safety" class="section safety" data-section="11"><div class="wrap split"><div>${label(11,'FOR YOUR SAFETY')}${heading('こんなときは、\nまず医療機関へ')}${image('treatment-hands','身体の状態を大切にしながら行うケア')}</div><div>${p(s(11)[0])}${list(s(11)[1],'safety-list')}${p(s(11)[2])}</div></div></section>`);
pages.push(`<section id="access" class="section access" data-section="12"><div class="wrap"><div class="split"><div>${label(12,'ACCESS')}${heading(copy[11].title)}<p class="salon-name">total life support <strong>clear</strong></p>${p(s(12)[2])}<dl>${s(12).slice(3).map(b=>{const [k,v]=b.split('\n');return `<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`}).join('')}</dl></div><div class="access-visual">${image('shop-exterior','おおにし産婦人科の外観。clearは2階です。')}${p(s(12)[1].replace(/^・/,''))}${btn('地図を見る',map,'button-green')}</div></div></div></section>`);
pages.push(`<section id="message" class="section message dark" data-section="13"><div class="wrap message-layout"><div class="message-aside">${label(13,'FROM CLEAR')}${heading(s(13)[0])}<figure>${image('selfcare-exercise','これからの身体との付き合い方を、一緒に考えるclearのケア')}<figcaption aria-hidden="true">Your body. Your life.</figcaption></figure></div><div class="message-copy">${s(13).slice(1,7).map(x=>p(x)).join('')}${fromButton(s(13)[7])}</div></div></section>`);
require('./design-details.cjs')({pages,image});
if(wpSettings.hero.enabled) {
  for(const key of ['desktopUrl','mobileUrl']) {
    if(!/^https:\/\//.test(wpSettings.hero[key])) throw new Error('Hero requires valid HTTPS desktopUrl and mobileUrl.');
  }
  const intro=pages[0].slice(pages[0].indexOf('<div class="hero-intro wrap">'));
  pages[0]=`<section id="home" class="hero hero-art" data-section="01"><div class="hero-accessible"><p>${esc(s(1)[0])}</p><h1>${esc(s(1)[1])}</h1>${p(s(1)[2])}${p(s(1)[5])}</div><picture class="hero-art-picture"><source media="(max-width: 767px)" srcset="${esc(wpSettings.hero.mobileUrl)}" width="941" height="1672"><img src="${esc(wpSettings.hero.desktopUrl)}" width="1672" height="941" alt="" fetchpriority="high" decoding="async"></picture><div class="hero-art-action wrap">${fromButton(s(1)[6])}</div>${intro}`;
}
require('./section-media.cjs')({pages,settings:wpSettings,btn});
const html=`<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#344b40"><meta name="description" content="鹿児島市川上町・おおにし産婦人科2Fの整体サロンclear。理学療法士が身体の状態を確認し、施術から運動・セルフケアまで一緒に考えます。完全個室・駐車場完備。"><title>clear｜鹿児島市川上町の整体・運動・セルフケア</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"></head><body>
<a class="skip-link" href="#main">本文へ移動</a><header class="site-header"><a class="brand" href="#home" aria-label="clear トップへ"><span>total life support</span><strong>clear<span class="brand-dot">.</span></strong></a><nav class="desktop-nav" aria-label="メインメニュー"><a href="#approach">clearの考え方</a><a href="#profile">プロフィール</a><a href="#price">料金</a><a href="#access">アクセス</a></nav><a class="header-book" href="#reservation">ご予約・ご相談 <span aria-hidden="true">↗</span></a></header>
<main id="main">${pages.join('\n')}</main><footer class="site-footer"><div class="wrap footer-inner"><a class="brand" href="#home"><span>total life support</span><strong>clear<span class="brand-dot">.</span></strong></a><div><p>total life support clear｜整体</p><p>鹿児島県鹿児島市川上町2805-1 おおにし産婦人科2F</p></div><a href="#home" class="back-top" aria-label="ページの先頭へ">↑</a></div></footer>
<nav class="mobile-booking" aria-label="予約と相談"><a href="${line}" target="_blank" rel="noopener">公式LINEで相談 <span aria-hidden="true">↗</span></a><a href="${hp}" target="_blank" rel="noopener">空席確認・予約 <span aria-hidden="true">↗</span></a></nav>
</body></html>`;
const styledHtml=html.replace('<link rel="stylesheet" href="styles.css">','<link rel="stylesheet" href="fonts/clear-fonts.css"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="design-v2.css">');
fs.writeFileSync(path.join(__dirname,'index.html'),styledHtml);
console.log('Built index.html with '+pages.length+' approved-copy sections.');
require('./export-wordpress.cjs')({html:styledHtml,pages,settings:wpSettings});
